import type { LumoraSignal } from "@/types/lumora.signal";

export const DEFAULT_FALLBACK_SIGNALS: LumoraSignal[] = [
  {
    id: "fallback_signal_001",
    platform: "internal",
    title: "Global reaction wave forming around an unexpected cultural moment",
    summary: "Fallback signal pack used when upstream providers are unavailable.",
    language: "en",
    region: "global",
    keywords: ["culture", "reaction", "fallback"],
    hashtags: ["#culture", "#reaction"],
    url: undefined,
    authorHandle: "lumora_system",
    trust: "verified",
    lifecycle: "rising",
    emotionTags: ["curiosity", "awe"],
    velocityScore: 72,
    saturationScore: 18,
    attentionScore: 76,
    createdAt: Date.now() - 30 * 60 * 1000,
    updatedAt: Date.now() - 10 * 60 * 1000,
  },
  {
    id: "fallback_signal_002",
    platform: "internal",
    title: "Entertainment chatter is accelerating before clips spread widely",
    summary: "Internal fallback seed to prevent empty attention surfaces.",
    language: "en",
    region: "global",
    keywords: ["entertainment", "pretrend", "seed"],
    hashtags: ["#entertainment", "#seed"],
    url: undefined,
    authorHandle: "lumora_system",
    trust: "verified",
    lifecycle: "rising",
    emotionTags: ["curiosity", "joy"],
    velocityScore: 68,
    saturationScore: 16,
    attentionScore: 70,
    createdAt: Date.now() - 45 * 60 * 1000,
    updatedAt: Date.now() - 15 * 60 * 1000,
  },
  {
    id: "fallback_signal_003",
    platform: "internal",
    title: "Search and discussion patterns hint at a fresh breakout topic",
    summary: "Fallback signal tuned for discovery continuity and feed resilience.",
    language: "en",
    region: "global",
    keywords: ["search", "discussion", "breakout"],
    hashtags: ["#search", "#discussion"],
    url: undefined,
    authorHandle: "lumora_system",
    trust: "verified",
    lifecycle: "peaking",
    emotionTags: ["curiosity", "tension"],
    velocityScore: 74,
    saturationScore: 20,
    attentionScore: 78,
    createdAt: Date.now() - 90 * 60 * 1000,
    updatedAt: Date.now() - 20 * 60 * 1000,
  }
];
