
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('@prisma/client/runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  passwordHash: 'passwordHash',
  emailVerified: 'emailVerified',
  image: 'image',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CreatorScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  slug: 'slug',
  bio: 'bio',
  createdAt: 'createdAt'
};

exports.Prisma.PostScalarFieldEnum = {
  id: 'id',
  creatorId: 'creatorId',
  title: 'title',
  content: 'content',
  visibility: 'visibility',
  createdAt: 'createdAt'
};

exports.Prisma.MediaAssetScalarFieldEnum = {
  id: 'id',
  postId: 'postId',
  url: 'url',
  type: 'type',
  createdAt: 'createdAt'
};

exports.Prisma.SubscriptionTierScalarFieldEnum = {
  id: 'id',
  creatorId: 'creatorId',
  title: 'title',
  monthlyCents: 'monthlyCents',
  createdAt: 'createdAt'
};

exports.Prisma.SubscriptionScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tierId: 'tierId',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  creatorId: 'creatorId',
  title: 'title',
  priceCents: 'priceCents',
  createdAt: 'createdAt'
};

exports.Prisma.PurchaseScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  productId: 'productId',
  createdAt: 'createdAt'
};

exports.Prisma.SavedMomentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  creatorId: 'creatorId',
  postId: 'postId',
  timestampMs: 'timestampMs',
  createdAt: 'createdAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  action: 'action',
  createdAt: 'createdAt'
};

exports.Prisma.SellerScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  storeName: 'storeName',
  slug: 'slug',
  bio: 'bio',
  logo: 'logo',
  banner: 'banner',
  status: 'status',
  rating: 'rating',
  verified: 'verified',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InventoryScalarFieldEnum = {
  id: 'id',
  sellerId: 'sellerId',
  productId: 'productId',
  sku: 'sku',
  quantity: 'quantity',
  reserved: 'reserved',
  lowStockAt: 'lowStockAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CartScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CartItemScalarFieldEnum = {
  id: 'id',
  cartId: 'cartId',
  productId: 'productId',
  quantity: 'quantity',
  price: 'price',
  createdAt: 'createdAt'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  sellerId: 'sellerId',
  userId: 'userId',
  status: 'status',
  subtotal: 'subtotal',
  tax: 'tax',
  shipping: 'shipping',
  total: 'total',
  currency: 'currency',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  title: 'title',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  totalPrice: 'totalPrice'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  provider: 'provider',
  providerRef: 'providerRef',
  amount: 'amount',
  currency: 'currency',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.RefundScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  amount: 'amount',
  reason: 'reason',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.ReturnScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  reason: 'reason',
  approved: 'approved',
  createdAt: 'createdAt'
};

exports.Prisma.ShipmentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  carrier: 'carrier',
  trackingNumber: 'trackingNumber',
  status: 'status',
  shippedAt: 'shippedAt',
  deliveredAt: 'deliveredAt',
  createdAt: 'createdAt'
};

exports.Prisma.PayoutScalarFieldEnum = {
  id: 'id',
  sellerId: 'sellerId',
  amount: 'amount',
  currency: 'currency',
  processed: 'processed',
  createdAt: 'createdAt'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  sellerId: 'sellerId',
  userId: 'userId',
  rating: 'rating',
  comment: 'comment',
  createdAt: 'createdAt'
};

exports.Prisma.ZendoroSellerScalarFieldEnum = {
  id: 'id',
  ownerId: 'ownerId',
  slug: 'slug',
  displayName: 'displayName',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ZendoroProductScalarFieldEnum = {
  id: 'id',
  sellerId: 'sellerId',
  slug: 'slug',
  title: 'title',
  description: 'description',
  priceCents: 'priceCents',
  currency: 'currency',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ZendoroCartScalarFieldEnum = {
  id: 'id',
  buyerId: 'buyerId',
  currency: 'currency',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ZendoroCartItemScalarFieldEnum = {
  id: 'id',
  cartId: 'cartId',
  productId: 'productId',
  quantity: 'quantity',
  unitPrice: 'unitPrice'
};

exports.Prisma.ZendoroOrderScalarFieldEnum = {
  id: 'id',
  buyerId: 'buyerId',
  status: 'status',
  subtotalCents: 'subtotalCents',
  totalCents: 'totalCents',
  currency: 'currency',
  idempotencyKey: 'idempotencyKey',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ZendoroOrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  totalPrice: 'totalPrice'
};

exports.Prisma.ZendoroPaymentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  provider: 'provider',
  providerPaymentId: 'providerPaymentId',
  status: 'status',
  amountCents: 'amountCents',
  currency: 'currency',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ZendoroRefundScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  amountCents: 'amountCents',
  reason: 'reason',
  createdAt: 'createdAt'
};

exports.Prisma.ZendoroReturnScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  reason: 'reason',
  createdAt: 'createdAt'
};

exports.Prisma.ZendoroShipmentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  trackingNumber: 'trackingNumber',
  carrier: 'carrier',
  createdAt: 'createdAt'
};

exports.Prisma.ZendoroPayoutScalarFieldEnum = {
  id: 'id',
  sellerId: 'sellerId',
  amountCents: 'amountCents',
  currency: 'currency',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.ZendoroReviewScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  buyerId: 'buyerId',
  rating: 'rating',
  body: 'body',
  createdAt: 'createdAt'
};

exports.Prisma.ZendoroInventoryScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  stock: 'stock',
  reserved: 'reserved',
  updatedAt: 'updatedAt'
};

exports.Prisma.StripeCheckoutSessionScalarFieldEnum = {
  id: 'id',
  stripeSession: 'stripeSession',
  userId: 'userId',
  status: 'status',
  credits: 'credits',
  amountCents: 'amountCents',
  currency: 'currency',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.PrivateBetaAccessScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  email: 'email',
  inviteCodeHash: 'inviteCodeHash',
  status: 'status',
  approvedBy: 'approvedBy',
  approvedAt: 'approvedAt',
  revokedAt: 'revokedAt',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RuntimeSignalScalarFieldEnum = {
  id: 'id',
  type: 'type',
  videoId: 'videoId',
  timestampMs: 'timestampMs',
  createdAt: 'createdAt'
};

exports.Prisma.ObservabilityEventScalarFieldEnum = {
  id: 'id',
  category: 'category',
  eventType: 'eventType',
  severity: 'severity',
  source: 'source',
  route: 'route',
  sessionId: 'sessionId',
  userId: 'userId',
  testerId: 'testerId',
  targetId: 'targetId',
  message: 'message',
  durationMs: 'durationMs',
  value: 'value',
  metadata: 'metadata',
  occurredAt: 'occurredAt',
  createdAt: 'createdAt'
};

exports.Prisma.ErrorReportScalarFieldEnum = {
  id: 'id',
  level: 'level',
  name: 'name',
  message: 'message',
  stack: 'stack',
  route: 'route',
  userAgent: 'userAgent',
  sessionId: 'sessionId',
  userId: 'userId',
  metadata: 'metadata',
  occurredAt: 'occurredAt',
  createdAt: 'createdAt'
};

exports.Prisma.ObservabilityRateLimitBucketScalarFieldEnum = {
  key: 'key',
  scope: 'scope',
  windowStart: 'windowStart',
  count: 'count',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmmlSnapshotScalarFieldEnum = {
  id: 'id',
  health: 'health',
  heatSampleSize: 'heatSampleSize',
  indicesTracked: 'indicesTracked',
  marketsOnline: 'marketsOnline',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  composite: 'composite',
  indicesJson: 'indicesJson',
  marketsJson: 'marketsJson',
  metaJson: 'metaJson'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.UserRole = exports.$Enums.UserRole = {
  fan: 'fan',
  creator: 'creator',
  moderator: 'moderator',
  admin: 'admin'
};

exports.SellerStatus = exports.$Enums.SellerStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  BANNED: 'BANNED'
};

exports.OrderStatus = exports.$Enums.OrderStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
};

exports.PaymentStatus = exports.$Enums.PaymentStatus = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

exports.RefundStatus = exports.$Enums.RefundStatus = {
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED'
};

exports.ShipmentStatus = exports.$Enums.ShipmentStatus = {
  PENDING: 'PENDING',
  PACKED: 'PACKED',
  SHIPPED: 'SHIPPED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  RETURNED: 'RETURNED'
};

exports.ZendoroSellerStatus = exports.$Enums.ZendoroSellerStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  BANNED: 'BANNED'
};

exports.ZendoroOrderStatus = exports.$Enums.ZendoroOrderStatus = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  PAID: 'PAID',
  FULFILLED: 'FULFILLED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
};

exports.ZendoroPaymentStatus = exports.$Enums.ZendoroPaymentStatus = {
  CREATED: 'CREATED',
  REQUIRES_ACTION: 'REQUIRES_ACTION',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

exports.PrivateBetaAccessStatus = exports.$Enums.PrivateBetaAccessStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REVOKED: 'REVOKED'
};

exports.Prisma.ModelName = {
  User: 'User',
  Creator: 'Creator',
  Post: 'Post',
  MediaAsset: 'MediaAsset',
  SubscriptionTier: 'SubscriptionTier',
  Subscription: 'Subscription',
  Product: 'Product',
  Purchase: 'Purchase',
  SavedMoment: 'SavedMoment',
  AuditLog: 'AuditLog',
  Seller: 'Seller',
  Inventory: 'Inventory',
  Cart: 'Cart',
  CartItem: 'CartItem',
  Order: 'Order',
  OrderItem: 'OrderItem',
  Payment: 'Payment',
  Refund: 'Refund',
  Return: 'Return',
  Shipment: 'Shipment',
  Payout: 'Payout',
  Review: 'Review',
  ZendoroSeller: 'ZendoroSeller',
  ZendoroProduct: 'ZendoroProduct',
  ZendoroCart: 'ZendoroCart',
  ZendoroCartItem: 'ZendoroCartItem',
  ZendoroOrder: 'ZendoroOrder',
  ZendoroOrderItem: 'ZendoroOrderItem',
  ZendoroPayment: 'ZendoroPayment',
  ZendoroRefund: 'ZendoroRefund',
  ZendoroReturn: 'ZendoroReturn',
  ZendoroShipment: 'ZendoroShipment',
  ZendoroPayout: 'ZendoroPayout',
  ZendoroReview: 'ZendoroReview',
  ZendoroInventory: 'ZendoroInventory',
  StripeCheckoutSession: 'StripeCheckoutSession',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  PrivateBetaAccess: 'PrivateBetaAccess',
  RuntimeSignal: 'RuntimeSignal',
  ObservabilityEvent: 'ObservabilityEvent',
  ErrorReport: 'ErrorReport',
  ObservabilityRateLimitBucket: 'ObservabilityRateLimitBucket',
  EmmlSnapshot: 'EmmlSnapshot'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
