name: CC Tower — AAA Game Pipeline

on:
  push:
    branches: [ main, master ]
    paths:
      - "src/**"
      - ".github/workflows/cc-tower.yml"
      - "package.json"
      - "tsconfig.json"
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Unit Tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: CC Tower Scan
        run: npm run cc:scan

      - name: CC Tower Report
        run: npm run cc:report
