import QuantumMirror from "@/app/_client/quantum-mirror";
import AutoRecovery from "@/app/_client/auto-recovery";
import SelfBenchmark from "@/app/_client/self-benchmark";
import OfflinePredict from "@/app/_client/offline-predict";
import OfflineCompress from "@/app/_client/offline-compress";
import DeltaSync from "@/app/_client/delta-sync";
import OfflineRewardTracker from "@/app/_client/offline-reward-tracker";
import AIFaultHealer from "@/app/_client/ai-fault-healer";
import ZenRecovery from "@/app/_client/zen-recovery";
import SyncStatusIndicator from "@/app/_client/sync-status-indicator";
import OfflineStateCapsule from "@/app/_client/offline-state-capsule";
import EmotionBridge from "@/app/_client/emotion-bridge";
import AdaptiveCachePruner from "@/app/_client/adaptive-cache-pruner";
import HoloContinuity from "@/app/_client/holo-continuity";
import SmartStashManager from "@/app/_client/smart-stash";
import MetricsQueue from "@/app/_client/metrics-queue";
import ProximityMagic from "@/app/_client/proximity-magic";
import LocalAiNode from "@/app/_client/local-ai-node";
import SyncRitual from "@/app/_client/sync-ritual";
import PwaRegister from "@/app/_client/pwa-register";
import QuantumMirrorMount from "./_client/QuantumMirrorMount";
import QuantumMirrorWrapper from "./_client/QuantumMirrorWrapper";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


import "./_styles/emoji.css";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <QuantumMirrorWrapper />
      <QuantumMirror />
      <AutoRecovery />
      <SelfBenchmark />
      <OfflinePredict />
      <OfflineCompress />
      <DeltaSync />
      <OfflineRewardTracker />
      <AIFaultHealer />
      <ZenRecovery />
      <SyncStatusIndicator />
      <OfflineStateCapsule />
      <EmotionBridge />
        <div id="light-flash" className="light-flash" />
        {children}
        <PwaRegister />
      <SyncRitual />
      <LocalAiNode />
  <ProximityMagic />
  <MetricsQueue />
      <SmartStashManager />
      <HoloContinuity />
      <AdaptiveCachePruner />
    </body>
    </html>
  );
}

import "./_styles/holo.css";
