export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (\n    <div id="light-flash" className="light-flash" />\n    <html lang="en">
      <body>{children}  <div id="lumora-light" className="light-flash"></div>
</body>
    </html>
  )
}

import "./_styles/icons.css";

import "./_styles/icons-holo.css";

import "./_styles/emoji.css";
